### ISSUE TITLE
Settings deprecation warning in container

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#3375]
**Describe the bug**
The ``
WARNING: "set" is deprecated and will be removed in future version. Please use `settings.path.to.key := value`
`` message doesn't display when running liquidsoap in containers.

**To Reproduce**

```ruby
settings.log.level.set(2)
```
```ruby
settings.init.allow_root.set(true)
```

**Expected behavior**

Liquidsoap should print a warning message.

**Version details**

- OS: Debian in docker
- Version: *2.2.1+git@de9dc76e1*

**Install method**
`savonet/liquidsoap:rolling-release-v2.2.x`

**Common issues**
N/A

**Comment by toots** [comment]
Thanks for reporting. This is weird, I'll have a look at it.

**Comment by vitoyucepi** [comment]
Reproduced on 2addd93, 528bd6d.

https://github.com/vitoyucepi/liquidsoap-issue-3375

<details>
<summary><code>main.liq</code></summary>

```ruby
set("log.level", 2)
print(settings.log.level())

set("init.allow_root", true)
print(settings.init.allow_root())

settings.log.level.set(4)
print(settings.log.level())

settings.init.allow_root.set(false)
print(settings.init.allow_root())

print(liquidsoap.version)
```

</details>
<details>
<summary><code>compose.yaml</code></summary>

```yaml
services:
  ls20:
    image: savonet/liquidsoap:rolling-release-v2.0.x
    command: /tmp/test/main.liq
    volumes:
      - ./:/tmp/test/
  ls21:
    image: savonet/liquidsoap:rolling-release-v2.1.x
    command: /tmp/test/main.liq
    volumes:
      - ./:/tmp/test/
  ls22:
    image: savonet/liquidsoap:rolling-release-v2.2.x
    command: /tmp/test/main.liq
    volumes:
      - ./:/tmp/test/
  ls23:
    image: savonet/liquidsoap:rolling-release-v2.3.x
    command: /tmp/test/main.liq
    volumes:
      - ./:/tmp/test/
```

</details>

I expected the reproduction to be an easy task, 20 minutes in and out.
https://github.com/vitoyucepi/liquidsoap-issue-3375
https://github.com/vitoyucepi/liquidsoap-issue-3375/actions/runs/12494098792
https://github.com/savonet/liquidsoap/blob/d2cc55985085d98b545d05e47a7b24dd6159a903/src/core/builtins/builtins_settings.ml#L271-L273

The deprecation warning is only displayed when the script has something to do.
<details>
<summary><code>main.liq</code></summary>

```ruby
set("log.level", 5)
print(settings.log.level())

set("init.allow_root", true)
print(settings.init.allow_root())

settings.log.level.set(4)
print(settings.log.level())

settings.init.allow_root.set(false)
print(settings.init.allow_root())

%ifversion >= 2.2
settings.log.level := 2
print(settings.log.level())

settings.init.allow_root := true
print(settings.init.allow_root())
%endif

print(liquidsoap.version)

output.dummy(sine())
thread.run({exit(0)}, delay=5.)
```

</details>
