### ISSUE TITLE
`check_next` is evaluated after request resolution

### ISSUE THREAD

**Issue by vitoyucepi** [savonet/liquidsoap#3625]
**Describe the bug**
The `playlist.list` function describes the `check_next` parameter as follows 
> The function is called before resolution
https://github.com/savonet/liquidsoap/blob/e536a5761eb2fd648a9b28f62256f4b3ee6aae53/src/libs/playlist.liq#L175-L180

But in reality, it's done after resolution.
https://github.com/savonet/liquidsoap/blob/e536a5761eb2fd648a9b28f62256f4b3ee6aae53/src/libs/playlist.liq#L361-L410

**To Reproduce**
1. Generate music and pictures
   ```sh
   mkdir music;
   convert -size 600x600 plasma: music/cover.png;
   ffmpeg -f lavfi -i "sine=frequency=100:duration=1" music/1.mp3;
   ```
1. `compose.yaml`
   ```yaml
   version: "3.8"
   services:
     liquidsoap:
       image: savonet/liquidsoap:v2.2.3
       command:
         - "/tmp/test/main.liq"
       volumes:
         - ./:/tmp/test
   ```
1. `main.liq`
   ```
   settings.log.level := 1

   def check_next(r)
     log.critical("#{request.uri(r)}")
     false
   end

   s = mksafe(playlist("/tmp/test/music", mode="normal", check_next=check_next))
   s = clock(sync="none", s)
   output.dummy(s)
   ```

**Expected behavior**
I'd like to use `check_next` to prevent resolution of image or garbage files before they are decoded.

**Version details**

- OS: Debian in docker container
- Version: *2.2.3*, *e536a57*

**Install method**
*savonet/liquidsoap:v2.2.3*

**Common issues**
N/A
