### ISSUE TITLE
The container fails to start due to an error.

### ISSUE THREAD

**Issue by AprilTim** [savonet/liquidsoap#4476]
### Description

I'm trying to run Icecast and Liquidsoap in Docker, but I keep getting the same error and Liquidsoap keeps restarting. Icecast is working fine.

### Steps to reproduce

This is the minimal folder structure of the project.

project
           |--configs
           |               |--radio.liq
           |               |--icecast.xml
           |
           |--tracks
           |             |--c1ef06cd094d826fa3db53010941d3d8.mp3
           |             |--disco_elysium.mp3
           |
           |--docker-compose.yml

This is my docker-compose file:

```
version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: obmazdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  icecast:
    image: infiniteproject/icecast
    container_name: icecast
    ports:
      - "8000:8000"
    volumes:
      - ./configs/icecast.xml:/etc/icecast2/icecast.xml:ro
    restart: unless-stopped

  liquidsoap:
    image: savonet/liquidsoap:v2.3.2
    container_name: liquidsoap
    volumes:
      - ./configs:/liquidsoap
      - ./tracks:/tracks
    command: liquidsoap /liquidsoap/default.liq
    depends_on:
      - icecast
    restart: unless-stopped

volumes:
  postgres_data:
```

This is icecast.xml

```
<icecast>
  <limits>
    <clients>100</clients>
    <sources>2</sources>
    <threadpool>5</threadpool>
    <queue-size>524288</queue-size>
    <client-timeout>30</client-timeout>
  </limits>

  <authentication>
    <source-password>hackme</source-password>
    <admin-user>admin</admin-user>
    <admin-password>admin</admin-password>
  </authentication>

  <hostname>localhost</hostname>

  <listen-socket>
    <port>8000</port>
  </listen-socket>

  <mount>
    <mount-name>/radio</mount-name>
    <password>hackme</password>
  </mount>

  <fileserve>1</fileserve>
</icecast>
```

### Expected behavior

So that the image in the container stops constantly restarting and everything starts working :)

### Log extracts

2025-05-04 16:56:05 liquidsoap        | Unknown position:
2025-05-04 16:56:05 liquidsoap        | 
2025-05-04 16:56:05 liquidsoap        | Error -1: Exception raised: Sys_error("Is a directory")
2025-05-04 16:56:05 liquidsoap        | Raised by primitive operation at Stdlib.input in file "stdlib.ml", line 423, characters 7-32
2025-05-04 16:56:05 liquidsoap        | Called from Sedlexing.Chan.ensure_bytes_available in file "src/lib/sedlexing.ml", line 331, characters 17-60
2025-05-04 16:56:05 liquidsoap        | Called from Sedlexing.make_from_channel.refill.loop in file "src/lib/sedlexing.ml", line 367, characters 10-71
2025-05-04 16:56:05 liquidsoap        | Called from Sedlexing.refill in file "src/lib/sedlexing.ml" (inlined), line 190, characters 10-56
2025-05-04 16:56:05 liquidsoap        | Called from Sedlexing.__private__next_int in file "src/lib/sedlexing.ml", line 210, characters 33-79
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Lexer.token.__sedlex_state_0 in file "_none_", line 0, characters 254-1023
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Lexer.token in file "_none_", line 0, characters 254-1023
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Preprocessor.mk_tokenizer.(fun) in file "src/lang/preprocessor.ml", line 28, characters 10-28
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Preprocessor.includer.token in file "src/lang/preprocessor.ml", line 119, characters 10-20
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Preprocessor.eval_ifdefs.token in file "src/lang/preprocessor.ml", line 49, characters 10-22
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Preprocessor.parse_comments.token in file "src/lang/preprocessor.ml", line 454, characters 10-22
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Preprocessor.expand_string.token in file "src/lang/preprocessor.ml", line 184, characters 12-24
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Preprocessor.int_meth.fill in file "src/lang/preprocessor.ml", line 476, characters 10-22
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Preprocessor.dotvar.token in file "src/lang/preprocessor.ml", line 505, characters 16-28
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Preprocessor.uminus.token in file "src/lang/preprocessor.ml", line 518, characters 10-22
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Preprocessor.strip_newlines.token in file "src/lang/preprocessor.ml", line 561, characters 16-28
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Preprocessor.mk_tokenizer.(fun) in file "src/lang/preprocessor.ml", line 582, characters 28-40
2025-05-04 16:56:05 liquidsoap        | Called from MenhirLib.Convert.traditional2revised.lexer in file "lib/pack/menhirLib.ml", line 152, characters 27-34
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Parser._menhir_run_506 in file "src/lang/parser.ml", line 14658, characters 17-45
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Runtime.from_lexbuf.(fun) in file "src/lang/runtime.ml", line 230, characters 17-62
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Runtime.report in file "src/lang/runtime.ml" (inlined), line 215, characters 12-23
2025-05-04 16:56:05 liquidsoap        | Called from Liquidsoap_lang__Runtime.from_lexbuf in file "src/lang/runtime.ml", li

### Script extracts

radio = single("/tracks/disco_elysium.mp3")

output.icecast(
  %mp3,
  host = "icecast",
  port = 8000,
  password = "hackme",
  mount = "/radio",
  name = "adio",
  genre = "Mixed",
  url = "http://localhost:8000/radio",
  radio
)

### Liquidsoap version

```text
image: savonet/liquidsoap:v2.3.2
```

### Liquidsoap build config

```text
I can't get it because the container keeps restarting.
```

### Installation method

From official container image
